/*Proyecto Sweet Seasons*/

--Creacion de las tablas
--Tabla de Clientes
CREATE TABLE CLIENTE (
ID_CLIENTE NUMBER(10) NOT NULL,
NOMBRE VARCHAR2(30) NOT NULL,
PRIMER_APELLIDO VARCHAR2(30) NOT NULL,
SEGUNDO_APELLIDO VARCHAR2(30) NOT NULL,
CORREO VARCHAR2(30),
NUMERO_TELEFONICO NUMBER(8),
DIRECCION VARCHAR2(30),
CONSTRAINT CLIENTE_PK PRIMARY KEY (ID_CLIENTE));

--Tabla de Ventas
CREATE TABLE VENTAS (
ID_VENTA NUMBER (10) NOT NULL,
FECHA_VENTA DATE  NOT NULL,
CANTIDAD INT NOT NULL,
PRECIO INT NOT NULL,
ID_CLIENTE NUMBER(10) NOT NULL,
ID_PRODUCTOS NUMBER(10) NOT NULL,
CONSTRAINT VENTAS_PK PRIMARY KEY (ID_VENTA),
CONSTRAINT VENTAS_CLIENTE_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
CONSTRAINT VENTAS_PRODUCTOS_FK FOREIGN KEY (ID_PRODUCTOS) REFERENCES PRODUCTOS(ID_PRODUCTOS)
);




--Creacion tabla ingredientes
CREATE TABLE INGREDIENTES(
ID_INGREDIENTE NUMBER NOT NULL,
NOMBRE_INGREDIENTE VARCHAR2(25)NOT NULL,
UNIDAD_MEDIDA VARCHAR2(20)NOT NULL,
PRECIO NUMBER NOT NULL,
CANTIDAD NUMBER NOT NULL,
ID_PROVEEDOR NUMBER NOT NULL
)

--CREACION TABLA PROVEEDORES
CREATE TABLE PROVEEDORES(
ID_PROVEEDOR NUMBER NOT NULL,
NOMBRE_PROVEEDOR VARCHAR2(50)NOT NULL,
PRIMER_APELLIDO VARCHAR2(50)NOT NULL,
SEGUNDO_APELLIDO VARCHAR2(50)NOT NULL,
NUMERO_TELEFONICO NUMBER(20) NOT NULL,
CORREO_ELECTRONICO VARCHAR2(50)NOT NULL,
ESTADO VARCHAR2(50)NOT NULL)

--Creacion Tabla de Categoria Productos
CREATE TABLE CATEGORIA_PRODUCTOS (
ID_CATEGORIA NUMBER(10) NOT NULL,
NOMBRE VARCHAR2(30) NOT NULL,
DESCRIPCION VARCHAR2(50) NOT NULL,
CONSTRAINT CAT_PRODUCTOS_PK PRIMARY KEY (ID_CATEGORIA)
);

--Creacion Tabla de Productos
CREATE TABLE PRODUCTOS (
ID_PRODUCTOS NUMBER(10) NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
ID_CATEGORIA NUMBER(10) NOT NULL,
CANTIDAD NUMBER(10) NOT NULL,
DESCRIPCION VARCHAR2(100),
TAMANO VARCHAR(10),
PRECIO NUMBER(20),
CONSTRAINT PRODUCTOS_PK PRIMARY KEY (ID_PRODUCTOS),
CONSTRAINT CATEGORIA_PRODUCTOS_FK FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_PRODUCTOS(ID_CATEGORIA)
);

CREATE TABLE COMPRAS(
    ID_COMPRA NUMBER NOT NULL,
    FECHA_COMPRA DATE,
    ID_PROVEEDOR NUMBER NOT NULL,
    ID_PRODUCTOS NUMBER NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO INT NOT NULL,
    TOTAL INT NOT NULL,
    CONSTRAINT COMPRAS_PK PRIMARY KEY (ID_COMPRA),
    CONSTRAINT COMPRAS_PROVEEDORES_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR),
    CONSTRAINT COMPRAS_PRODUCTOS_FK FOREIGN KEY (ID_PRODUCTOS) REFERENCES PRODUCTOS(ID_PRODUCTOS)
);


--CREACION DE LLAVES PRIMARIAS
ALTER TABLE INGREDIENTES
ADD CONSTRAINT PK_INGREDIENTES PRIMARY KEY(ID_INGREDIENTE);

ALTER TABLE PROVEEDORES
ADD CONSTRAINT PK_PROVEEDORES PRIMARY KEY (ID_PROVEEDOR);
--CREACION DE LLAVES FORANEAS

ALTER TABLE INGREDIENTES
ADD CONSTRAINT FK_IDPROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES
(ID_PROVEEDOR);

--Inserts 
--Inserts a Clientes
Insert into CLIENTE (ID_CLIENTE,NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,CORREO,NUMERO_TELEFONICO,DIRECCION) 
values (1,'Pablo','Lopez','Rodriguez','pablo.rodri@gmail.com',87349012,'Heredia Central');
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO, NUMERO_TELEFONICO, DIRECCION)
VALUES (2, 'Maria', 'Gomez', 'Fernandez', 'maria.fernandez@gmail.com', 78901234, 'San Jose');
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO, NUMERO_TELEFONICO, DIRECCION)
VALUES (3, 'Carlos', 'Martinez', 'Lopez', 'carlos.lopez@gmail.com', 65432178, 'Cartago');
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO, NUMERO_TELEFONICO, DIRECCION)
VALUES (4, 'Laura', 'Ramirez', 'Perez', 'laura.perez@gmail.com', 98761234, 'Alajuela');
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO, NUMERO_TELEFONICO, DIRECCION)
VALUES (5, 'Juan', 'Gonzalez', 'Sanchez', 'juan.sanchez@gmail.com', 12345678, 'Puntarenas');
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO, NUMERO_TELEFONICO, DIRECCION)
VALUES (6, 'Ana', 'Hernandez', 'Mendez', 'ana.mendez@gmail.com', 87654321, 'Guanacaste');
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO, NUMERO_TELEFONICO, DIRECCION)
VALUES (7, 'Diego', 'Castro', 'Jimenez', 'diego.jimenez@gmail.com', 56781234, 'Limon');
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO, NUMERO_TELEFONICO, DIRECCION)
VALUES (8, 'Sofia', 'Perez', 'Gonzalez', 'sofia.gonzalez@gmail.com', 89123456, 'San Jose');
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO, NUMERO_TELEFONICO, DIRECCION)
VALUES (9, 'Luis', 'Sanchez', 'Hernandez', 'luis.hernandez@gmail.com', 76543219, 'Heredia');
INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO, NUMERO_TELEFONICO, DIRECCION)
VALUES (10, 'Monica', 'Jimenez', 'Ramirez', 'monica.ramirez@gmail.com', 91234567, 'Alajuela');

--Inserts a Ventas
INSERT INTO VENTAS (ID_VENTA,FECHA_VENTA,CANTIDAD,PRECIO,ID_CLIENTE,ID_PRODUCTOS) 
VALUES (1,'2023-10-21',2,10500.00,1,'1');
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA, CANTIDAD, PRECIO, ID_CLIENTE, ID_PRODUCTOS)
VALUES (2, '2023-10-22', 3, 7500.00, 2, 2);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA, CANTIDAD, PRECIO, ID_CLIENTE, ID_PRODUCTOS)
VALUES (3, '2023-10-23', 1, 12000.00, 3, 3);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA, CANTIDAD, PRECIO, ID_CLIENTE, ID_PRODUCTOS)
VALUES (4, '2023-10-24', 4, 9000.00, 4, 4);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA, CANTIDAD, PRECIO, ID_CLIENTE, ID_PRODUCTOS)
VALUES (5, '2023-10-25', 2, 8000.00, 5, 5);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA, CANTIDAD, PRECIO, ID_CLIENTE, ID_PRODUCTOS)
VALUES (6, '2023-10-26', 3, 9500.00, 6, 1);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA, CANTIDAD, PRECIO, ID_CLIENTE, ID_PRODUCTOS)
VALUES (7, '2023-10-27', 1, 11000.00, 7, 2);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA, CANTIDAD, PRECIO, ID_CLIENTE, ID_PRODUCTOS)
VALUES (8, '2023-10-28', 5, 8500.00, 8, 3);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA, CANTIDAD, PRECIO, ID_CLIENTE, ID_PRODUCTOS)
VALUES (9, '2023-10-29', 2, 7500.00, 9, 4);
INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA, CANTIDAD, PRECIO, ID_CLIENTE, ID_PRODUCTOS)
VALUES (10, '2023-10-30', 3, 10000.00, 10, 5);

--Inserts a Categorias de Productos:
Insert into CATEGORIA_PRODUCTOS (ID_CATEGORIA, NOMBRE, DESCRIPCION) 
values (1,'Cupcakes','Pequenos y deliciosos cupcakes');
Insert into CATEGORIA_PRODUCTOS (ID_CATEGORIA, NOMBRE, DESCRIPCION) 
values (2,'Brownies','Irresistibles brownies de chocolate');
Insert into CATEGORIA_PRODUCTOS (ID_CATEGORIA, NOMBRE, DESCRIPCION) 
values (3,'Panes','Panes frescos y deliciosos');
Insert into CATEGORIA_PRODUCTOS (ID_CATEGORIA, NOMBRE, DESCRIPCION) 
values (4,'Pasteles','Pasteles unicos y deliciosos');

--Inserts a Productos:
-- Cupcakes
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (1, 'Cupcake Vainilla', 1, 30, 'Cupcake suave de vainilla', 'PEQUENO', 7000);
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (2, 'Cupcake Chocolate', 1, 25, 'Cupcake delicioso de chocolate', 'MEDIANO', 8500);
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (3, 'Cupcake Fresa', 1, 20, 'Cupcake con relleno de fresa', 'GRANDE', 12000);
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (4, 'Cupcake Moka', 1, 18, 'Cupcake con sabor a moka', 'MEDIANO', 9500);
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (5, 'Cupcake Caramelo', 1, 22, 'Cupcake con decoracion de caramelo', 'GRANDE', 13000);

-- Brownies
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (6, 'Brownie Nuez', 2, 15, 'Brownie de chocolate con nueces', 'PEQUENO', 5500);
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (7, 'Brownie Chocolate Blanco', 2, 20, 'Brownie con chocolate blanco', 'MEDIANO', 7000);
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (8, 'Brownie Frutas Rojas', 2, 25, 'Brownie con frutas rojas', 'GRANDE', 11000);
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (9, 'Brownie Caramelo Salado', 2, 18, 'Brownie con caramelo salado', 'MEDIANO', 8000);
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (10, 'Brownie Menta', 2, 22, 'Brownie con sabor a menta', 'GRANDE', 15000);

-- Panes
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (11, 'Pan Integral', 3, 28, 'Pan integral recien horneado', 'MEDIANO', 7500);
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (12, 'Pan Multicereales', 3, 35, 'Pan con una mezcla de cereales', 'GRANDE', 10000);
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (13, 'Pan Centeno', 3, 22, 'Pan de centeno con semillas', 'PEQUENO', 6000);
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (14, 'Pan Avena', 3, 30, 'Pan con copos de avena', 'MEDIANO', 8500);
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (15, 'Pan Nuez y Miel', 3, 18, 'Pan con nueces y miel', 'GRANDE', 12000);

-- Pasteles
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (16, 'Pastel Fresa y Chocolate', 4, 20, 'Pastel con capas de fresa y chocolate', 'PEQUENO', 8000);
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (17, 'Pastel Tres Leches', 4, 25, 'Pastel esponjoso con tres tipos de leche', 'MEDIANO', 11000);
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (18, 'Pastel Zanahoria', 4, 30, 'Pastel de zanahoria con crema de queso', 'GRANDE', 15000);
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (19, 'Pastel Manzana Canela', 4, 22, 'Pastel con manzanas y canela', 'MEDIANO', 9500);
Insert into PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO) 
values (20, 'Pastel Selva Negra', 4, 18, 'Pastel con capas de chocolate y cerezas', 'PEQUENO', 7000);


--Proveedores
-- Insertar proveedor 1
INSERT INTO PROVEEDORES (ID_PROVEEDOR, NOMBRE_PROVEEDOR, PRIMER_APELLIDO, SEGUNDO_APELLIDO, NUMERO_TELEFONICO, CORREO_ELECTRONICO, ESTADO)
VALUES (1, 'Juan', 'GÃ³mez', 'LÃ³pez', 123456789, 'juan.gomez@hotmail.com', 'Activo');
INSERT INTO PROVEEDORES (ID_PROVEEDOR, NOMBRE_PROVEEDOR, PRIMER_APELLIDO, SEGUNDO_APELLIDO, NUMERO_TELEFONICO, CORREO_ELECTRONICO, ESTADO)
VALUES (2, 'MarÃ­a', 'HernÃ¡ndez', 'MartÃ­nez', 987654321, 'maria.hernandez@gmail.com', 'Inactivo');
INSERT INTO PROVEEDORES (ID_PROVEEDOR, NOMBRE_PROVEEDOR, PRIMER_APELLIDO, SEGUNDO_APELLIDO, NUMERO_TELEFONICO, CORREO_ELECTRONICO, ESTADO)
VALUES (3, 'Pedro', 'DÃ­az', 'GarcÃ­a', 555555555, 'pedro.diaz@hotmail.com', 'Activo');

--Compras
INSERT INTO COMPRAS (ID_COMPRA, FECHA_COMPRA, ID_PROVEEDOR, ID_PRODUCTOS, CANTIDAD, PRECIO, TOTAL)
VALUES (1, TO_DATE('01-01-2023', 'DD-MM-YYYY'), 1, 1, 10, 50, 500);
INSERT INTO COMPRAS (ID_COMPRA, FECHA_COMPRA, ID_PROVEEDOR, ID_PRODUCTOS, CANTIDAD, PRECIO, TOTAL)
VALUES (2, TO_DATE('05-01-2023', 'DD-MM-YYYY'), 3, 3, 15, 40, 600);
INSERT INTO COMPRAS (ID_COMPRA, FECHA_COMPRA, ID_PROVEEDOR, ID_PRODUCTOS, CANTIDAD, PRECIO, TOTAL)
VALUES (3, TO_DATE('10-01-2023', 'DD-MM-YYYY'), 1, 4, 20, 30, 600);
INSERT INTO COMPRAS (ID_COMPRA, FECHA_COMPRA, ID_PROVEEDOR, ID_PRODUCTOS, CANTIDAD, PRECIO, TOTAL)
VALUES (4, TO_DATE('15-01-2023', 'DD-MM-YYYY'), 2, 11, 12, 45, 540);
INSERT INTO COMPRAS (ID_COMPRA, FECHA_COMPRA, ID_PROVEEDOR, ID_PRODUCTOS, CANTIDAD, PRECIO, TOTAL)
VALUES (5, TO_DATE('20-01-2023', 'DD-MM-YYYY'), 3, 3, 18, 35, 630);


--Procedure para ingresar datos
--Clientes
CREATE OR REPLACE PROCEDURE INSERT_CLIENTES (
    IDE CLIENTE.ID_CLIENTE%TYPE,
    NOM CLIENTE.NOMBRE%TYPE,
    PRIMER_AP CLIENTE.PRIMER_APELLIDO%TYPE,
    SEGUNDO_AP CLIENTE.SEGUNDO_APELLIDO%TYPE,
    COR CLIENTE.CORREO%TYPE,
    NUMERO CLIENTE.NUMERO_TELEFONICO%TYPE,
    DIREC CLIENTE.DIRECCION%TYPE)
AS
BEGIN 
    INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO,
    NUMERO_TELEFONICO, DIRECCION)
    VALUES (IDE, NOM, PRIMER_AP, SEGUNDO_AP, COR, NUMERO, DIREC);
    COMMIT;
END;
    
EXEC INSERT_CLIENTES (10, 'Monica', 'Jimenez', 'Ramirez', 'monica.ramirez@gmail.com', 91234567, 'Alajuela');

--Ventas
CREATE OR REPLACE PROCEDURE INSERT_VENTAS (
    IDE VENTAS.ID_VENTA%TYPE,
    FECHA VENTAS.FECHA_VENTA%TYPE,
    CANT VENTAS.CANTIDAD%TYPE,
    PREC VENTAS.PRECIO%TYPE,
    ID_C VENTAS.ID_CLIENTE%TYPE,
    ID_P VENTAS.ID_PRODUCTOS%TYPE)
AS
BEGIN 
    INSERT INTO VENTAS (ID_VENTA,FECHA_VENTA,CANTIDAD,PRECIO,ID_CLIENTE,ID_PRODUCTOS)
    VALUES (IDE, FECHA, CANT, PREC, ID_C, ID_P);
    COMMIT;
END;
    
EXEC INSERT_VENTAS (10, '2023-10-30', 3, 10000.00, 10, 5);

--PROCEDURE PARA ACTUALIZAR UN DATO
--Clientes
CREATE OR REPLACE PROCEDURE UPDATE_CLIENTES (
    IDE CLIENTE.ID_CLIENTE%TYPE,
    NOM CLIENTE.NOMBRE%TYPE,
    PRIMER_AP CLIENTE.PRIMER_APELLIDO%TYPE,
    SEGUNDO_AP CLIENTE.SEGUNDO_APELLIDO%TYPE,
    COR CLIENTE.CORREO%TYPE,
    NUMERO CLIENTE.NUMERO_TELEFONICO%TYPE,
    DIREC CLIENTE.DIRECCION%TYPE)
AS
BEGIN 
    UPDATE CLIENTE 
    SET NOMBRE = NOM,
        PRIMER_APELLIDO = PRIMER_AP,
        SEGUNDO_APELLIDO = SEGUNDO_AP,
        CORREO = COR,
        NUMERO_TELEFONICO = NUMERO,
        DIRECCION=DIREC
    WHERE ID_CLIENTE = IDE;
END;
    
EXEC INSERT_CLIENTES (10, 'Monica', 'Jimenez', 'Ramirez', 'monica.ramirez@gmail.com', 91234567, 'Alajuela');

CREATE OR REPLACE PROCEDURE UPDATE_VENTAS (
    IDE VENTAS.ID_VENTA%TYPE,
    FECHA VENTAS.FECHA_VENTA%TYPE,
    CANT VENTAS.CANTIDAD%TYPE,
    PREC VENTAS.PRECIO%TYPE,
    ID_C VENTAS.ID_CLIENTE%TYPE,
    ID_P VENTAS.ID_PRODUCTOS%TYPE)
AS
BEGIN 
    UPDATE VENTAS 
    SET FECHA_VENTA = FECHA,
        CANTIDAD = CANT,
        PRECIO = PREC,
        ID_CLIENTE = ID_C,
        ID_PRODUCTOS = ID_P
    WHERE ID_VENTA = IDE;
END;
EXEC UPDATE_VENTAS (15, '30-NOV-23', 1, 1000.00, 1, 1);

SELECT * FROM VENTAS;
 
--VIEW PARA READ
--CLIENTES
CREATE VIEW READ_CLIENTE AS
SELECT NOMBRE,PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO, NUMERO_TELEFONICO, DIRECCION
FROM CLIENTE
ORDER BY NOMBRE;

--Procedimiento para ejecutar el read clientes
CREATE OR REPLACE PROCEDURE P_READ_CLIENTE (resultados OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN resultados FOR SELECT * FROM READ_CLIENTE;
END;

EXEC P_READ_CLIENTE;

SET SERVEROUTPUT ON

--VENTAS
CREATE VIEW READ_VENTAS AS
SELECT FECHA_VENTA,CANTIDAD,PRECIO,ID_CLIENTE,ID_PRODUCTOS
FROM VENTAS
ORDER BY FECHA_VENTA;

--Procedimiento para ejecutar el read ventas
CREATE OR REPLACE PROCEDURE P_READ_VENTAS (resultados OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN resultados FOR SELECT * FROM READ_VENTAS;
END;

EXEC P_READ_VENTAS;

-- FUNCTION PARA ELIMINAR DATOS DE UNA TABLA
--CLIENTES
CREATE OR REPLACE FUNCTION DELETE_CLIENTES (IDE VARCHAR2) RETURN VARCHAR2
IS
BEGIN
    DELETE FROM CLIENTE
    WHERE ID_CLIENTE = IDE;
    RETURN 'Datos eliminados correctamente';
END;

--Para ejecutarlo
CREATE OR REPLACE PROCEDURE Ej_Func_Client(IDE VARCHAR2)
IS
    resultado VARCHAR2(100);
BEGIN
    resultado := DELETE_CLIENTES(IDE); 
    DBMS_OUTPUT.PUT_LINE(resultado);
END;

EXEC Ej_Func_Client(11);

--VENTAS
CREATE OR REPLACE FUNCTION DELETE_VENTAS (IDE VARCHAR2) RETURN VARCHAR2
IS
BEGIN
    DELETE FROM VENTAS
    WHERE ID_VENTA = IDE;
    RETURN 'Datos eliminados correctamente';
END;


--Para ejecutarlo
CREATE OR REPLACE PROCEDURE Ej_Func_Vent(IDE NUMBER)
IS
    resultado VARCHAR2(100);
BEGIN
    resultado := DELETE_VENTAS(IDE); -- Llama a la funciÃÂ³n DELETE_VENTAS
    DBMS_OUTPUT.PUT_LINE(resultado);
END;

EXEC Ej_Func_Vent(10);

--CURSORES
--funcion para traer el nombre completo del cliente con el total que compro en una venta
DECLARE 
    cur_clie_to SYS_REFCURSOR;
    NOM CLIENTE.NOMBRE%TYPE;
    PRIMER_AP CLIENTE.PRIMER_APELLIDO%TYPE;
    SEGUNDO_AP CLIENTE.SEGUNDO_APELLIDO%TYPE;
    FECHA VENTAS.FECHA_VENTA%TYPE;
BEGIN 
    OPEN cur_clie_to FOR SELECT c.NOMBRE, c.PRIMER_APELLIDO, c.SEGUNDO_APELLIDO, v.FECHA_VENTA 
    FROM CLIENTE c
    INNER JOIN VENTAS v  ON c.ID_CLIENTE=v.ID_CLIENTE
    WHERE v.ID_VENTA = 9;
    
    FETCH cur_clie_to INTO NOM, PRIMER_AP, SEGUNDO_AP, FECHA;
    CLOSE cur_clie_to;
    
     DBMS_OUTPUT.PUT_LINE( NOM || ' ' || PRIMER_AP || ' ' || SEGUNDO_AP || ' hizo una compra en la fecha ' || FECHA);
END;

--funcion para traer el nombre  del producto con el total que compro en una venta
DECLARE 
    cur_pro_ven SYS_REFCURSOR;
    NOM PRODUCTOS.NOMBRE%TYPE;
    FECHA VENTAS.FECHA_VENTA%TYPE;
    CANT VENTAS.CANTIDAD%TYPE;
BEGIN 
    OPEN cur_pro_ven FOR SELECT p.NOMBRE, v.CANTIDAD, v.FECHA_VENTA
    FROM PRODUCTOS p
    INNER JOIN VENTAS v  ON p.ID_PRODUCTOS=v.ID_PRODUCTOS
    WHERE v.ID_VENTA = 9;
    
    FETCH cur_pro_ven INTO NOM, CANT, FECHA;
    CLOSE cur_pro_ven;
    
     DBMS_OUTPUT.PUT_LINE( 'Se compro '|| CANT || ' '  || NOM || ' en la fecha ' || FECHA );
END;

--PROVEEDORES E INGREDIENTES

--PROCEDIMIENTOS ALMACENADOS
--1-PROCEDIMIENTO PARA AGREGAR LOS DATOS DE PROVEEDORES 1
CREATE OR REPLACE PROCEDURE AGREGAR_PROVEEDOR(ID_PRO IN NUMBER,NOMBRE IN VARCHAR2,
PAPELLIDO IN VARCHAR2,SAPELLIDO IN VARCHAR2, TELEFONO IN NUMBER,CORREO IN VARCHAR2,
ESTADO IN VARCHAR2)
AS
BEGIN
INSERT INTO PROVEEDORES(ID_PROVEEDOR ,NOMBRE_PROVEEDOR ,PRIMER_APELLIDO,
SEGUNDO_APELLIDO ,NUMERO_TELEFONICO ,CORREO_ELECTRONICO ,ESTADO)
VALUES (ID_PRO,NOMBRE,PAPELLIDO,SAPELLIDO,TELEFONO,CORREO,ESTADO);
END;

--PRUEBA DEL PROCEDIMIENO
EXEC AGREGAR_PROVEEDOR(2,'JUAN','MORA','ABARCA',24101726,'ROBERTO@GMAIL.COM','ACTIVO');
--2-PROCEDIMIENTO PARA AGREGAR LOS DATOS DE INGREDIENTES 1
CREATE OR REPLACE PROCEDURE AGREGAR_INGREDIENTE(ID_INGREDIENTE IN NUMBER,NOMBRE IN VARCHAR2,
UNIDAD IN VARCHAR2, PRECIO NUMBER,CANTIDAD IN NUMBER,ID_PROVEEDOR IN NUMBER)
AS
BEGIN
INSERT INTO INGREDIENTES(ID_INGREDIENTE,NOMBRE_INGREDIENTE,UNIDAD_MEDIDA ,
PRECIO,CANTIDAD,ID_PROVEEDOR)
VALUES(ID_INGREDIENTE ,NOMBRE,UNIDAD, PRECIO,CANTIDAD,ID_PROVEEDOR);
END;
--PRUEBA DEL PROCEDIMIENO
EXEC AGREGAR_INGREDIENTE(1,'AZUCAR','KILOGRAMOS',700,2,2);
SELECT * FROM INGREDIENTES;

--3-PROCEDIMIENTO PARA ACTUALIZAR EL PRECIO DE UN INGREDIENTE 1
CREATE OR REPLACE PROCEDURE ACTUALIZAR_INGREDIENTE_PRECIO(IDINGRE IN NUMBER,PRECIONUEVO IN NUMBER)
AS
BEGIN
UPDATE INGREDIENTES SET PRECIO=PRECIONUEVO WHERE ID_INGREDIENTE=IDINGRE;
END;
--PRUEBA PROCEDIMEINTO ACUTUALIZAR PRECIO
EXEC ACTUALIZAR_INGREDIENTE_PRECIO(1,750);



EXEC ELIMINAR_PROVEEDOR_ESPECIFICO(2);

--4-PROCEDIEMIENTO PARA ACTUALIZAR LA CANTIDAD DE UN INGREDIENTE 2
CREATE OR REPLACE PROCEDURE ACTUALIZAR_CANTIDAD_INGREDIENTE(ID_BUSCADO IN 
NUMBER, CANTIDAD_NUEVA IN NUMBER)
AS
BEGIN
UPDATE INGREDIENTES SET CANTIDAD=CANTIDAD_NUEVA WHERE ID_INGREDIENTE =ID_BUSCADO;
END;
--EJECUCION
EXEC ACTUALIZAR_CANTIDAD_INGREDIENTE(1,4);

--5-PROCEDIMIENTO PARA VER UN PROVEEDOR EN ESPECIFICO
CREATE OR REPLACE PROCEDURE VER_PROVEEDOR_ESPECIFICO(ID_BUSCADO IN NUMBER)
AS
BEGIN
SELECT * FROM PROVEEDORES WHERE PROVEEDOR_ID=ID_BUSCADO

--VISTA VER TODOS LOS INGREDIENTES
CREATE VIEW VER_INGREDIENTES AS
SELECT ID_INGREDIENTE,NOMBRE_INGREDIENTE,UNIDAD_MEDIDA
,PRECIO,CANTIDAD, ID_PROVEEDOR
FROM INGREDIENTES ORDER BY ID_INGREDIENTE;

--METODO PARA LEER LA VISTA DE VER INGREDIENTES
CREATE OR REPLACE PROCEDURE LEER_INGREDIENTES(resultados OUT SYS_REFCURSOR)
IS BEGIN
    OPEN RESULTADOS FOR SELECT * FROM VER_INGREDIENTES;
END;

--PRUEBA VISTA VER TODOS LOS PROVEEDORES
SELECT * FROM  VER_INGREDIENTES;


--VISTA VER TODOS LOS PROVEEDORES
CREATE VIEW VER_PROVEEDORES AS
SELECT ID_PROVEEDOR, NOMBRE_PROVEEDOR,PRIMER_APELLIDO,
SEGUNDO_APELLIDO, NUMERO_TELEFONICO, CORREO_ELECTRONICO,
ESTADO FROM PROVEEDORES ORDER BY ID_PROVEEDOR;

CREATE OR REPLACE PROCEDURE LEER_PROVEEDOR(resultados OUT SYS_REFCURSOR)
IS BEGIN
    OPEN RESULTADOS FOR SELECT * FROM VER_PROVEEDORES;
END;


--CREACION DE FUNCIONES
CREATE OR REPLACE FUNCTION CANTIDAD_PROVEEDORES
RETURN NUMBER
IS
    CANTIDAD NUMBER; 
    BEGIN
    SELECT COUNT(ID_PROVEEDOR) INTO CANTIDAD
    FROM PROVEEDORES;   
    RETURN CANTIDAD;
END;
--PROBAR FUNCION
SELECT CANTIDAD_PROVEEDORES FROM DUAL;

CREATE OR REPLACE FUNCTION CANTIDAD_INGREDIENTES
RETURN NUMBER
IS
    CANTIDAD NUMBER; 
    BEGIN
    SELECT COUNT(ID_INGREDIENTE) INTO CANTIDAD
    FROM INGREDIENTES;   
    RETURN CANTIDAD;
END;

--PROBAR FUNCION
SELECT CANTIDAD_INGREDIENTES FROM DUAL;


--CREACION DE CURSOR PARA ACTUALIZAR DATOS DEL PROVEEDOR
CREATE OR REPLACE PROCEDURE ACTUALIZAR_PROVE(ID_BUSCADO IN NUMBER,NOMBRE IN VARCHAR2,
PAPELLIDO IN VARCHAR2,SAPELLIDO IN VARCHAR2, NUMERO IN NUMBER,CORREO IN VARCHAR2,
EST IN VARCHAR2)
IS

CURSOR ACTUALIZAR_PROVEEDOR IS SELECT *
    FROM PROVEEDORES;
     PROVEEDOR_C ACTUALIZAR_PROVEEDOR%ROWTYPE;
 BEGIN    
     OPEN ACTUALIZAR_PROVEEDOR;  
     FETCH ACTUALIZAR_PROVEEDOR INTO PROVEEDOR_C;
        
     UPDATE PROVEEDORES
     SET NOMBRE_PROVEEDOR=NOMBRE, PRIMER_APELLIDO=PAPELLIDO,SEGUNDO_APELLIDO=SAPELLIDO,
     NUMERO_TELEFONICO=NUMERO,CORREO_ELECTRONICO=CORREO, ESTADO=EST
     WHERE ID_PROVEEDOR=ID_BUSCADO;
       
CLOSE ACTUALIZAR_PROVEEDOR;
END;    
 --PRUEBA    
EXEC ACTUALIZAR_PROVE(2,'JUAN','MORA','ABARCA',24101726,'JUAN@GMAIL.COM','INACTIVO');

--FUNCION ELIMINAR INGREDIENTE
CREATE OR REPLACE FUNCTION ELIMINAR_INGREDIENTE (IDE VARCHAR2) RETURN VARCHAR2
IS
BEGIN
    DELETE FROM INGREDIENTES
    WHERE ID_INGREDIENTE = IDE;
    RETURN 'Datos eliminados correctamente';
END;

--PROCEDIEMIENTO PARA EJECUTAR LA FUNCION
CREATE OR REPLACE PROCEDURE Ej_ELIMINAR_INGREDIENTE(IDE VARCHAR2)
IS
    resultado VARCHAR2(100);
BEGIN
    resultado := ELIMINAR_INGREDIENTE(IDE); 
    DBMS_OUTPUT.PUT_LINE(resultado);
END;

--ELIMINAR PROVEEDOR FUNCION

CREATE OR REPLACE FUNCTION ELIMINAR_PROVEEDOR (IDE VARCHAR2) RETURN VARCHAR2
IS
BEGIN
    DELETE FROM PROVEEDORES
    WHERE ID_PROVEEDOR = IDE;
    RETURN 'Datos eliminados correctamente';
END;

--Para ejecutarlo PROCEDIMIENTO
CREATE OR REPLACE PROCEDURE Ej_ELIMINAR_PROVEEDOR(IDE VARCHAR2)
IS
    resultado VARCHAR2(100);
BEGIN
    resultado := ELIMINAR_PROVEEDOR(IDE); 
    DBMS_OUTPUT.PUT_LINE(resultado);
END;



--CREACION DE CURSOR PARA ACTUALIZAR TODOS LOS DATOS DE UN INGREDIENTE 2
CREATE OR REPLACE PROCEDURE ACTUALIZAR_INGREDIENTES(ID_BUSCADO IN NUMBER,NOMBRE IN VARCHAR2,
UNIDAD IN VARCHAR2,PRECIONU IN NUMBER, CANTIDADNU IN NUMBER,ID_PROV IN NUMBER)
IS

CURSOR ACTUALIZAR_INGREDIENTE IS SELECT *
    FROM INGREDIENTES;
     INGREDIENTE_C ACTUALIZAR_INGREDIENTE%ROWTYPE;
 BEGIN    
     OPEN ACTUALIZAR_INGREDIENTE;  
     FETCH ACTUALIZAR_INGREDIENTE INTO INGREDIENTE_C;
        
     UPDATE INGREDIENTES
     SET NOMBRE_INGREDIENTE=NOMBRE, UNIDAD_MEDIDA=UNIDAD,PRECIO=PRECIONU,
     CANTIDAD=CANTIDADNU,ID_PROVEEDOR=ID_PROV
     WHERE ID_INGREDIENTE=ID_BUSCADO;
       
CLOSE ACTUALIZAR_INGREDIENTE;
END;    
 --PRUEBA    
EXEC ACTUALIZAR_INGREDIENTES(1,'AZUCAR','KILOGRAMOS',750,24,'2');
SELECT * FROM INGREDIENTES;






--FIN PROVEEDORES E INGREDIENTES





---------------- PROCEDIMIENTOS ALMACENADOS CATEGORIAS Y PRODUCTOS ---------------

-- SP para Categorias

-- 1) Procedimiento para agregar/insertar una categoria

CREATE OR REPLACE PROCEDURE ADD_CATEGORY (
    p_id_categoria IN NUMBER,
    p_nombre IN VARCHAR2,
    p_descripcion IN VARCHAR2
)
AS
BEGIN
    INSERT INTO CATEGORIA_PRODUCTOS (ID_CATEGORIA, NOMBRE, DESCRIPCION)
    VALUES (p_id_categoria, p_nombre, p_descripcion);    
    COMMIT;
END;

/* El siguiente EXEC para testeo nada mas! */
EXEC ADD_CATEGORY(6, 'TestName', 'DescripciÃ³n de test Category');

-- 2) Procedimiento para eliminar una categoria

CREATE OR REPLACE PROCEDURE DELETE_CATEGORY (
    p_id_categoria IN NUMBER
)
AS
BEGIN
    DELETE FROM CATEGORIA_PRODUCTOS
    WHERE ID_CATEGORIA = p_id_categoria;
    COMMIT;
END;

/* El siguiente EXEC para testeo nada mas! */
EXEC DELETE_CATEGORY(6);

-- 3) Procedimiento para actualizar nombre de una categoria

CREATE OR REPLACE PROCEDURE UPDATE_CATEGORY_NAME (
    p_id_categoria IN NUMBER,
    p_nuevo_nombre IN VARCHAR2
)
AS
BEGIN
    UPDATE CATEGORIA_PRODUCTOS
    SET NOMBRE = p_nuevo_nombre
    WHERE ID_CATEGORIA = p_id_categoria;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DescripciÃ³n de la categorÃ­a actualizada con Ã©xito.');
END;

/* El siguiente EXEC para testeo nada mas! */
EXEC UPDATE_CATEGORY_NAME(5, 'Nuevo nombre actualizada');

-- 4) Procedimiento para actualizar descripcion de una categoria

CREATE OR REPLACE PROCEDURE UPDATE_CATEGORY_DESCRIPTION (
    p_id_categoria IN NUMBER,
    p_nueva_descripcion IN VARCHAR2
)
AS
BEGIN
    UPDATE CATEGORIA_PRODUCTOS
    SET DESCRIPCION = p_nueva_descripcion
    WHERE ID_CATEGORIA = p_id_categoria;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DescripciÃ³n de la categorÃ­a actualizada con Ã©xito.');
END;

/* El siguiente EXEC para testeo nada mas! */
EXEC UPDATE_CATEGORY_DESCRIPTION(5, 'Nueva descripciÃ³n actualizada');

-- 5) Procedimiento para actualizar una categoria completa.

CREATE OR REPLACE PROCEDURE UPDATE_CATEGORY (
    IDE CATEGORIA_PRODUCTOS.ID_CATEGORIA%TYPE,
    NOM CATEGORIA_PRODUCTOS.NOMBRE%TYPE,
    DESCRIPCION CATEGORIA_PRODUCTOS.DESCRIPCION%TYPE
) AS
BEGIN 
    UPDATE CATEGORIA_PRODUCTOS 
    SET NOMBRE = NOM,
        DESCRIPCION = DESCRIPCION
    WHERE ID_CATEGORIA = IDE;
END UPDATE_CATEGORY;
/

-- 6) Procedimiento para ejecutar el read de categoria

--VIEW PARA READ
--CATEGORIES
CREATE VIEW READ_CATEGORY AS
SELECT NOMBRE,DESCRIPCION
FROM CATEGORIA_PRODUCTOS
ORDER BY NOMBRE;


CREATE OR REPLACE PROCEDURE P_READ_CATEGORIA (resultados OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN resultados FOR SELECT * FROM READ_CATEGORY;
END;

EXEC P_READ_CATEGORIA;





-- SP para Productos

-- 1) Procedimiento para agregar nuevos productos.

CREATE OR REPLACE PROCEDURE ADD_PRODUCTOS (
    p_id_producto IN NUMBER,
    p_nombre IN VARCHAR2,
    p_id_categoria IN NUMBER,
    p_cantidad IN NUMBER,
    p_descripcion IN VARCHAR2,
    p_tamano IN VARCHAR2,
    p_precio IN NUMBER
)
AS
BEGIN
    INSERT INTO PRODUCTOS (ID_PRODUCTOS, NOMBRE, ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO)
    VALUES (p_id_producto, p_nombre, p_id_categoria, p_cantidad, p_descripcion, p_tamano, p_precio);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Producto agregado con Ã©xito.');
END;

-- 2) Procedimiento para eliminar un producto.

-- FUNCTION PARA ELIMINAR DATOS DE UNA TABLA
--CLIENTES
CREATE OR REPLACE FUNCTION ELIMINAR_PRODUCTOS (IDE VARCHAR2) RETURN VARCHAR2
IS
BEGIN
    DELETE FROM PRODUCTOS
    WHERE ID_PRODUCTOS = IDE;
    RETURN 'Datos eliminados correctamente';
END;

--Para ejecutarlo
CREATE OR REPLACE PROCEDURE DELETE_PRODUCTOS(IDE VARCHAR2)
IS
    resultado VARCHAR2(100);
BEGIN
    resultado := ELIMINAR_PRODUCTOS(IDE); 
    DBMS_OUTPUT.PUT_LINE(resultado);
END;


-- 3) Procedimiento para actualizar la cantidad de un producto.

CREATE OR REPLACE PROCEDURE UPDATE_PRODUCTOS_CANTIDAD (
    p_id_producto IN NUMBER,
    p_nueva_cantidad IN NUMBER
)
AS
BEGIN
    UPDATE PRODUCTOS
    SET CANTIDAD = p_nueva_cantidad
    WHERE ID_PRODUCTOS = p_id_producto;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Cantidad del producto actualizada con Ã©xito.');
END;


-- 4) Procedimiento para actualizar el tamano de un producto.

CREATE OR REPLACE PROCEDURE UPDATE_PRODUCTOS_TAMANO (
    p_id_producto IN NUMBER,
    p_nuevo_tamano IN VARCHAR2
)
AS
BEGIN
    UPDATE PRODUCTOS
    SET TAMANO = p_nuevo_tamano
    WHERE ID_PRODUCTOS = p_id_producto;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('TamaÃ±o del producto actualizado con Ã©xito.');
END;


-- 5) Procedimiento para actualizar el precio de un producto.

CREATE OR REPLACE PROCEDURE UPDATE_PRODUCTOS_PRECIO (
    p_id_producto IN NUMBER,
    p_nuevo_precio IN NUMBER
)
AS
BEGIN
    UPDATE PRODUCTOS
    SET PRECIO = p_nuevo_precio
    WHERE ID_PRODUCTOS = p_id_producto;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Precio del producto actualizado con Ã©xito.');
END;


-- 6) Procedimiento para actualizar un producto completo

--PROCEDURE PARA ACTUALIZAR UN DATO
--Clientes
CREATE OR REPLACE PROCEDURE UPDATE_PRODUCTOS (
    IDE PRODUCTOS.ID_PRODUCTOS%TYPE,
    NOM PRODUCTOS.NOMBRE%TYPE,
    ID_CAT PRODUCTOS.ID_CATEGORIA%TYPE,
    CANT PRODUCTOS.CANTIDAD%TYPE,
    DESCRIPCION PRODUCTOS.DESCRIPCION%TYPE,
    TAMANO PRODUCTOS.TAMANO%TYPE,
    PRECIO PRODUCTOS.PRECIO%TYPE)
AS
BEGIN 
    UPDATE PRODUCTOS 
    SET NOMBRE = NOM,
        PRIMER_APELLIDO = ID_CAT,
        SEGUNDO_APELLIDO = CANT,
        CORREO = DESCRIPCION,
        NUMERO_TELEFONICO = TAMANO,
        DIRECCION=PRECIO
    WHERE ID_PRODUCTOS = IDE;
END;
/

--  PROCEDIMEINTO PARA READ PRODUCTOS

--VIEW PARA READ
--CLIENTES
CREATE VIEW READ_PRODUCTOS AS
SELECT NOMBRE,ID_CATEGORIA, CANTIDAD, DESCRIPCION, TAMANO, PRECIO
FROM PRODUCTOS
ORDER BY NOMBRE;

--Procedimiento para ejecutar el read clientes
CREATE OR REPLACE PROCEDURE P_READ_PRODUCTOS (resultados OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN resultados FOR SELECT * FROM READ_PRODUCTOS;
END;

EXEC P_READ_PRODUCTOS;




---------------- VISTAS CATEGORIAS Y PRODUCTOS ----------------------------

-- 1) Vista que muestra informacion detallada de productos con nombres de cateogira.

CREATE OR REPLACE VIEW VIEW_PRODUCTOS_CATEGORY AS
SELECT P.ID_PRODUCTOS, P.NOMBRE, P.CANTIDAD, P.DESCRIPCION, P.TAMANO, P.PRECIO, CP.NOMBRE AS NOMBRE_CATEGORIA
FROM PRODUCTOS P
JOIN CATEGORIA_PRODUCTOS CP ON P.ID_CATEGORIA = CP.ID_CATEGORIA;

-- 2) Vista para mostrar cantidad disponible de cada categoria:

CREATE OR REPLACE VIEW VIEW_CATEGORY_CANT_DISPONIBLE AS
SELECT CP.NOMBRE AS NOMBRE_CATEGORIA, SUM(P.CANTIDAD) AS CANTIDAD_TOTAL
FROM PRODUCTOS P
JOIN CATEGORIA_PRODUCTOS CP ON P.ID_CATEGORIA = CP.ID_CATEGORIA
GROUP BY CP.NOMBRE;

-- 3) Vista para mostrar cantidad de productos con cantidad baja

CREATE OR REPLACE VIEW VIEW_PRODUCTOS_CANT_BAJA AS
SELECT * FROM PRODUCTOS
WHERE CANTIDAD < 20;

-- 4) Vista para mostrar informacion de categorias con cantidad total de productos.

CREATE OR REPLACE VIEW VIEW_CATEGORY_CANT_TOTAL AS
SELECT CP.ID_CATEGORIA, CP.NOMBRE, CP.DESCRIPCION, COUNT(P.ID_PRODUCTOS) AS CANTIDAD_TOTAL
FROM CATEGORIA_PRODUCTOS CP
LEFT JOIN PRODUCTOS P ON CP.ID_CATEGORIA = P.ID_CATEGORIA
GROUP BY CP.ID_CATEGORIA, CP.NOMBRE, CP.DESCRIPCION;


-------------- FUNCIONES CATEGORIAS Y PRODUCTOS --------------------------

-- Obtener (lectura) informacion de un producto por categoria

CREATE OR REPLACE FUNCTION READ_CATEGORY (
    p_id_categoria IN NUMBER
)
RETURN VARCHAR2
AS
    v_info_categoria VARCHAR2(200);
BEGIN
    SELECT 'ID: ' || ID_CATEGORIA || ', Nombre: ' || NOMBRE || ', DescripciÃ³n: ' || DESCRIPCION
    INTO v_info_categoria
    FROM CATEGORIA_PRODUCTOS
    WHERE ID_CATEGORIA = p_id_categoria;

    RETURN v_info_categoria;
END;

-- Obtener (lectura) informacion de una categoria de producto.

CREATE OR REPLACE FUNCTION READ_PRODUCTOS (
    p_id_producto IN NUMBER
)
RETURN VARCHAR2
AS
    v_info_producto VARCHAR2(200);
BEGIN
    SELECT 'ID: ' || ID_PRODUCTOS || ', Nombre: ' || NOMBRE || ', Cantidad: ' || CANTIDAD ||
           ', DescripciÃ³n: ' || DESCRIPCION || ', TamaÃ±o: ' || TAMANO || ', Precio: ' || PRECIO
    INTO v_info_producto
    FROM PRODUCTOS
    WHERE ID_PRODUCTOS = p_id_producto;

    RETURN v_info_producto;
END;


--------------- CURSORES CATEGORIAS Y PRODUCTOS ----------------------------

-- 1) Cursor para recorrer y mostrar todos los productos de la tabla.

DECLARE
   CURSOR c_productos IS
      SELECT * FROM PRODUCTOS;
   v_producto PRODUCTOS%ROWTYPE;
BEGIN
   OPEN c_productos;
   LOOP
      FETCH c_productos INTO v_producto;
      EXIT WHEN c_productos%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('ID: ' || v_producto.ID_PRODUCTOS ||
                           ', Nombre: ' || v_producto.NOMBRE ||
                           ', Cantidad: ' || v_producto.CANTIDAD ||
                           ', DescripciÃ³n: ' || v_producto.DESCRIPCION ||
                           ', TamaÃ±o: ' || v_producto.TAMANO ||
                           ', Precio: ' || v_producto.PRECIO);
   END LOOP;
   CLOSE c_productos;
END;

-- 2) Cursor para mostrar productos de una categoria especifica.

DECLARE
   CURSOR c_productos_categoria(p_id_categoria NUMBER) IS
      SELECT * FROM PRODUCTOS
      WHERE ID_CATEGORIA = p_id_categoria;
   v_producto PRODUCTOS%ROWTYPE;
BEGIN
   OPEN c_productos_categoria(2);
   LOOP
      FETCH c_productos_categoria INTO v_producto;
      EXIT WHEN c_productos_categoria%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('ID: ' || v_producto.ID_PRODUCTOS ||
                           ', Nombre: ' || v_producto.NOMBRE ||
                           ', Cantidad: ' || v_producto.CANTIDAD ||
                           ', DescripciÃ³n: ' || v_producto.DESCRIPCION ||
                           ', TamaÃ±o: ' || v_producto.TAMANO ||
                           ', Precio: ' || v_producto.PRECIO);
   END LOOP;
   CLOSE c_productos_categoria;
END;

-- 3) Cursor para actualizar los precios de los productos de una categoria especifica aumentando sus precios en un 5%.

DECLARE
   CURSOR AUMENTAR_PRECIO_PORCIENTO IS
      SELECT ID_PRODUCTOS, PRECIO
      FROM PRODUCTOS
      WHERE ID_CATEGORIA = 1;

BEGIN
   FOR producto_rec IN AUMENTAR_PRECIO_PORCIENTO
   LOOP
      UPDATE PRODUCTOS
      SET PRECIO = producto_rec.PRECIO * 1.05
      WHERE ID_PRODUCTOS = producto_rec.ID_PRODUCTOS;
   END LOOP;

   COMMIT;

   DBMS_OUTPUT.PUT_LINE('Precios aumentados en un 5% para la categorÃ­a seleccionada.');
END;

-- 4) Cursor para actualizar los precios de una categoria especifica en reducirlos en un 10% en caso de un descuento promocion.

DECLARE
   
   CURSOR reducir_precio IS
      SELECT ID_PRODUCTOS, PRECIO
      FROM PRODUCTOS
      WHERE ID_CATEGORIA = 2; 
BEGIN
   FOR producto_rec IN reducir_precio
   LOOP
      UPDATE PRODUCTOS
      SET PRECIO = producto_rec.PRECIO * 0.9
      WHERE ID_PRODUCTOS = producto_rec.ID_PRODUCTOS;
   END LOOP;
   COMMIT;
   DBMS_OUTPUT.PUT_LINE('Precios reducidos en un 10% para la categorÃ­a seleccionada.');
END;


-----------------Procedimientos para COMPRAS----------------------------------

-- Procedimiento para insertar una nueva compra
CREATE OR REPLACE PROCEDURE insertar_compra(p_id_compra IN NUMBER,p_fecha_compra IN DATE,p_id_proveedor IN NUMBER,
  p_id_producto IN NUMBER,p_cantidad IN INT,p_precio IN INT,p_total IN INT) 
AS
BEGIN
  INSERT INTO COMPRAS (ID_COMPRA,FECHA_COMPRA,ID_PROVEEDOR,ID_PRODUCTOS,
  CANTIDAD,PRECIO,TOTAL) 
  VALUES (p_id_compra,p_fecha_compra,p_id_proveedor,p_id_producto,p_cantidad,
  p_precio,p_total);
END insertar_compra;

-- Procedimiento para actualizar una compra existente
CREATE OR REPLACE PROCEDURE actualizar_compra( p_id_compra IN NUMBER, 
p_cantidad IN INT, p_precio IN INT, p_total IN INT) 
AS
BEGIN
  UPDATE COMPRAS
  SET CANTIDAD = p_cantidad,
      PRECIO = p_precio,
      TOTAL = p_total
  WHERE ID_COMPRA = p_id_compra;
END actualizar_compra;

--Procedimiento para llamar la funcion de eliminar
CREATE OR REPLACE PROCEDURE EJ_FUNC_COMPRA(P_ID_COMPRA IN NUMBER)
IS
    V_RESULTADO VARCHAR2(100);
BEGIN
    V_RESULTADO := DELETE_COMPRA(P_ID_COMPRA);
    DBMS_OUTPUT.PUT_LINE(V_RESULTADO);
END;



-----------------------------Vistas para COMPRAS--------------------------------
-- Vista para obtener informacion detallada de las compras
CREATE OR REPLACE VIEW vista_compras AS
SELECT C.ID_COMPRA, C.FECHA_COMPRA, C.ID_PROVEEDOR, P.NOMBRE_PROVEEDOR, C.ID_PRODUCTOS,
  C.CANTIDAD, C.PRECIO, C.TOTAL
FROM COMPRAS C
JOIN PROVEEDORES P ON C.ID_PROVEEDOR = P.ID_PROVEEDOR;



-----------------------------Funciones para COMPRAS-----------------------------

-- Funcion para calcular el total de todas las compras
CREATE OR REPLACE FUNCTION calcular_total_compras RETURN INT 
AS
  v_total INT := 0;
BEGIN
  SELECT SUM(TOTAL) INTO v_total FROM COMPRAS;
  RETURN v_total;
END calcular_total_compras;

-- FunciÃ³n para obtener el proveedor con mÃ¡s compras
CREATE OR REPLACE FUNCTION proveedor_con_mas_compras RETURN VARCHAR2 
AS
  v_proveedor VARCHAR2(50);
BEGIN
  SELECT P.NOMBRE_PROVEEDOR
  INTO v_proveedor
  FROM COMPRAS C
  JOIN PROVEEDORES P ON C.ID_PROVEEDOR = P.ID_PROVEEDOR
  GROUP BY P.NOMBRE_PROVEEDOR
  ORDER BY COUNT(C.ID_COMPRA) DESC
  FETCH FIRST 1 ROW ONLY;
  RETURN v_proveedor;
END proveedor_con_mas_compras;

--Funcion para eliminar compra
create or replace NONEDITIONABLE FUNCTION DELETE_COMPRA(P_ID_COMPRA IN NUMBER) RETURN VARCHAR2
IS
BEGIN
    DELETE FROM COMPRAS
    WHERE ID_COMPRA = P_ID_COMPRA;
    RETURN 'Compra eliminada correctamente.';
END;

--Funcion para mostrar compras
CREATE OR REPLACE NONEDITIONABLE FUNCTION READ_COMPRAS
RETURN SYS_REFCURSOR
AS
    v_result SYS_REFCURSOR;
BEGIN
    OPEN v_result FOR
        SELECT 'ID Compra: ' || ID_COMPRA || ', Fecha: ' || TO_CHAR(FECHA_COMPRA, 'DD/MM/YYYY') || 
               ', ID Proveedor: ' || ID_PROVEEDOR || ', ID Productos: ' || ID_PRODUCTOS || 
               ', Cantidad: ' || CANTIDAD || ', Precio: ' || PRECIO || ', Total: ' || TOTAL AS INFO_COMPRA
        FROM COMPRAS;

    RETURN v_result;
END;




-----------------------------Cursores para COMPRAS-----------------------------

-- Crear un bloque PL/SQL
DECLARE
  CURSOR c_compras IS
    SELECT ID_COMPRA, FECHA_COMPRA FROM COMPRAS;
  v_id_compra COMPRAS.ID_COMPRA%TYPE;
  v_fecha_compra COMPRAS.FECHA_COMPRA%TYPE;
BEGIN
  OPEN c_compras;
  LOOP
    FETCH c_compras INTO v_id_compra, v_fecha_compra;
    EXIT WHEN c_compras%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('ID Compra: ' || v_id_compra || ', Fecha Compra: ' || v_fecha_compra); 
  END LOOP;
  CLOSE c_compras;
END;



-- Cursor para obtener compras de un proveedor especÃ­fico
CREATE OR REPLACE PROCEDURE OBTENER_COMPRAS_POR_PROVEEDOR(p_id_proveedor IN NUMBER) IS
  CURSOR c_compras_proveedor IS
    SELECT ID_COMPRA, FECHA_COMPRA 
    FROM COMPRAS 
    WHERE ID_PROVEEDOR = p_id_proveedor;
  
  v_id_compra_proveedor COMPRAS.ID_COMPRA%TYPE;
  v_fecha_compra_proveedor COMPRAS.FECHA_COMPRA%TYPE;
BEGIN
  OPEN c_compras_proveedor;
  LOOP
    FETCH c_compras_proveedor INTO v_id_compra_proveedor, v_fecha_compra_proveedor;

    EXIT WHEN c_compras_proveedor%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('ID Compra: ' || v_id_compra_proveedor || ', Fecha Compra: ' || v_fecha_compra_proveedor);
  END LOOP;
  CLOSE c_compras_proveedor;
END;

-------------------------------------------------TRIGGERS-------------------------------------------------------------
--table para registrar el trigger de actuilizar precios de productos
CREATE TABLE historial_precios (
    cambio_id INT GENERATED ALWAYS AS IDENTITY,
    id_productos INT,
    precio_anterior DECIMAL(20, 0),
    precio_nuevo DECIMAL(20, 0),
    fecha_cambio TIMESTAMP,
    PRIMARY KEY (cambio_id),
    FOREIGN KEY (id_productos) REFERENCES productos(id_productos)
);

--1. Trigger que registra datos al actualizar el precio de un producto
CREATE OR REPLACE TRIGGER tr_before_update_precio
BEFORE UPDATE ON productos
FOR EACH ROW
BEGIN
    IF :NEW.precio <> :OLD.precio THEN
        INSERT INTO historial_precios (id_productos, precio_anterior, precio_nuevo, fecha_cambio)
        VALUES (:OLD.id_productos, :OLD.precio, :NEW.precio, CURRENT_TIMESTAMP);
    END IF;
END;
--para probar
UPDATE productos SET precio = 7500 WHERE id_productos = 1;

--table para registrar el trigger de actuilizar precios de ingredientes
CREATE TABLE historial_precios_ing (
    cambio_ing_id INT GENERATED ALWAYS AS IDENTITY,
    id_ingrediente INT,
    precio_anterior DECIMAL(20, 0),
    precio_nuevo DECIMAL(20, 0),
    fecha_cambio TIMESTAMP,
    PRIMARY KEY (cambio_ing_id),
    FOREIGN KEY (id_ingrediente) REFERENCES ingredientes(id_ingrediente)
);

--2. Trigger que registra datos al actualizar el precio de un ingredientes
CREATE OR REPLACE TRIGGER tr_before_update_precio_ing
BEFORE UPDATE ON ingredientes
FOR EACH ROW
BEGIN
    IF :NEW.precio <> :OLD.precio THEN
        INSERT INTO historial_precios_ing (id_ingrediente, precio_anterior, precio_nuevo, fecha_cambio)
        VALUES (:OLD.id_ingrediente, :OLD.precio, :NEW.precio, CURRENT_TIMESTAMP);
    END IF;
END;
--inseta para probar
INSERT INTO ingredientes (id_ingrediente, nombre_ingrediente, unidad_medida, precio, cantidad, id_proveedor)
VALUES (1,'Harina','5 kilos',8000,2,1);
--prueba
UPDATE ingredientes SET precio = 8500 WHERE id_ingrediente = 1;


SET SERVEROUTPUT ON
--3. trigger que notifica las actualizaciones de un cliente
CREATE OR REPLACE TRIGGER tr_after_update_cliente
AFTER UPDATE ON cliente
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('InformaciÃ³n actualizada para el cliente ' || :NEW.id_cliente);
END;
--para probar
UPDATE CLIENTE SET CORREO = 'pablo_loro12@gmail.com' WHERE ID_CLIENTE = 1;

--4. trigger que notifica las actualizaciones de un proveedor
CREATE OR REPLACE TRIGGER tr_after_update_proveedor
AFTER UPDATE ON proveedores
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('InformaciÃ³n actualizada para el proveedor ' || :NEW.id_proveedor);
END;

--5. Trigger que menciona que no se vender algo con cantidad 0
CREATE OR REPLACE TRIGGER tr_before_insert_venta
BEFORE INSERT ON ventas
FOR EACH ROW
BEGIN
    IF :NEW.cantidad = 0 THEN
        DBMS_OUTPUT.PUT_LINE( 'No se puede vender un producto con cantidad igual a 0.');
    END IF;
END;
--para probar
INSERT INTO VENTAS (ID_VENTA,FECHA_VENTA,CANTIDAD,PRECIO,ID_CLIENTE,ID_PRODUCTOS) 
VALUES (11,'21-NOV-23',0,10500,1,1);

--------Cursores extras de clientes y proveedores -----------------
--CURSOR PARA CALCULAR LA CANTIDAD TOTAL DE VENTAS HECHAS A UN CLIENTE
CREATE OR REPLACE PROCEDURE compras_cliente(p_cliente_id NUMBER) AS
    v_total_compras NUMBER := 0;

    CURSOR compras_cursor IS
        SELECT precio
        FROM ventas
        WHERE id_cliente = p_cliente_id;

BEGIN
    v_total_compras := 0;

    FOR compra_rec IN compras_cursor LOOP
        v_total_compras := v_total_compras + compra_rec.precio;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('El cliente ' || p_cliente_id || ' ha gastado un total de ' || v_total_compras || ' en compras.');
END;

EXEC compras_cliente(1);

--CURSOR PARA CALCULAR LA CANTIDAD TOTAL DE COMPRAS HECHAS A UN PROVEEDOR
CREATE OR REPLACE PROCEDURE compras_proveedor(p_id_proveedor NUMBER) AS
    v_total_compras NUMBER := 0;

    CURSOR compras_cursor IS
        SELECT total
        FROM compras
        WHERE id_proveedor = p_id_proveedor;

BEGIN
    v_total_compras := 0;

    FOR compra_rec IN compras_cursor LOOP
        v_total_compras := v_total_compras + compra_rec.total;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Se le ha comprado al proveedor ' || p_id_proveedor || ' un total de ' || v_total_compras || ' en compras.');
END;

EXEC compras_proveedor(1);


/* ------- VISTA   */

-- 10) Vista "TOP VENTAS PRODUCTO" que busca mostrar los productos mas vendidos junto con la cantidad total de ventas.

CREATE VIEW TOP_VENTAS_PRODUCTO AS
SELECT
    P.ID_PRODUCTOS,
    P.NOMBRE AS NOMBRE_PRODUCTO,
    COUNT(V.ID_VENTA) AS NUMERO_VENTAS,
    SUM(V.CANTIDAD) AS CANTIDAD_TOTAL_VENDIDA,
    SUM(V.PRECIO) AS INGRESOS_TOTALES
FROM
    PRODUCTOS P
    JOIN VENTAS V ON P.ID_PRODUCTOS = V.ID_PRODUCTOS
GROUP BY
    P.ID_PRODUCTOS, P.NOMBRE
ORDER BY
    CANTIDAD_TOTAL_VENDIDA DESC;
    
-- Para probar a la vista
SELECT * FROM TOP_VENTAS_PRODUCTO;


-- 11) Vista de Clientes Frecuentes, que lista clientes que han realizado mas compras mostrando informacion de ellos

CREATE VIEW CLIENTES_FRECUENTES AS
SELECT
    C.ID_CLIENTE,
    C.NOMBRE || ' ' || C.PRIMER_APELLIDO AS NOMBRE_COMPLETO,
    COUNT(V.ID_VENTA) AS NUMERO_COMPRAS,
    SUM(V.PRECIO) AS MONTO_TOTAL_GASTADO
FROM
    CLIENTE C
    JOIN VENTAS V ON C.ID_CLIENTE = V.ID_CLIENTE
GROUP BY
    C.ID_CLIENTE, C.NOMBRE, C.PRIMER_APELLIDO
ORDER BY
    NUMERO_COMPRAS DESC;



-- Para probar a la vista
SELECT * FROM CLIENTES_FRECUENTES;

--------------------------------Funciones--------------------------------
--1. Calcular Impuesto sobre la Venta
CREATE OR REPLACE FUNCTION calcular_impuesto_venta(id_pro NUMBER) 
RETURN NUMBER IS
    p_monto_total NUMBER;
    v_impuesto NUMBER;
BEGIN
    SELECT precio INTO p_monto_total FROM productos  WHERE id_productos = id_pro;
    v_impuesto := p_monto_total * 0.13; --IVA 
    RETURN v_impuesto;
END;

--ejec
CREATE OR REPLACE PROCEDURE Ej_calcular_impuesto(IDE VARCHAR2)
IS
    resultado NUMBER;
BEGIN
    resultado := calcular_impuesto_venta(IDE); 
    DBMS_OUTPUT.PUT_LINE('El iva del producto es de ' || resultado);
END;

EXEC Ej_calcular_impuesto(1);

--2. Cant. de pedidos hechos por un cliente
CREATE OR REPLACE FUNCTION obtener_total_pedidos_cliente(p_id_cliente NUMBER) 
RETURN NUMBER IS
    v_total_pedidos NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_total_pedidos
    FROM ventas
    WHERE id_cliente = p_id_cliente;

    RETURN v_total_pedidos;
END;

--ejec
CREATE OR REPLACE PROCEDURE Ej_pedidos_cliente(IDE VARCHAR2)
IS
    resultado NUMBER;
BEGIN
    resultado := obtener_total_pedidos_cliente(IDE); 
    DBMS_OUTPUT.PUT_LINE('El total de ventas hechas al cliente es de  ' || resultado);
END;

EXEC Ej_pedidos_cliente(1);

--2. Cant. de pedidos hechos a un proveedor
CREATE OR REPLACE FUNCTION obtener_total_pedidos_proveedor(p_id_productos NUMBER) 
RETURN NUMBER IS
    v_total_pedidos NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_total_pedidos
    FROM compras
    WHERE id_productos = p_id_productos;

    RETURN v_total_pedidos;
END;

--ejec
CREATE OR REPLACE PROCEDURE Ej_pedidos_proveedor(IDE VARCHAR2)
IS
    resultado NUMBER;
BEGIN
    resultado := obtener_total_pedidos_proveedor(IDE); 
    DBMS_OUTPUT.PUT_LINE('El total de compras hechas al proveedor es de  ' || resultado);
END;

EXEC Ej_pedidos_proveedor(1);

--3. calcular Precio Final con Descuento
CREATE OR REPLACE FUNCTION calcular_precio_final(id_pro NUMBER,p_descuento NUMBER) 
RETURN NUMBER IS
    v_precio_final NUMBER;
    p_precio_base NUMBER;
BEGIN
    SELECT precio INTO p_precio_base FROM productos  WHERE id_productos = id_pro;
    v_precio_final := p_precio_base * (1 - p_descuento);
    RETURN v_precio_final;
END;

--ejec
CREATE OR REPLACE PROCEDURE Ej_calcular_precio_final(IDE NUMBER, DES NUMBER)
IS
    resultado NUMBER;
BEGIN
    resultado := calcular_precio_final(IDE,DES); 
    DBMS_OUTPUT.PUT_LINE('El precio total del producto con un descuento es de ' || resultado);
END;

EXEC Ej_calcular_precio_final(1,0.2);

--4. precio de la venta por compra al por mayor
CREATE OR REPLACE FUNCTION precio_por_mayor(id_ven  NUMBER) 
RETURN NUMBER IS
    v_precio_final NUMBER;
    p_precio_base NUMBER;
BEGIN
    SELECT precio INTO p_precio_base FROM ventas  WHERE id_venta = id_ven AND cantidad >= 12;
    v_precio_final := p_precio_base * (1 - 0.10);
    RETURN v_precio_final;
END;

--ejec
CREATE OR REPLACE PROCEDURE Ej_precio_por_mayor(IDE NUMBER)
IS
    resultado NUMBER;
BEGIN
    resultado := precio_por_mayor(IDE); 
    DBMS_OUTPUT.PUT_LINE('El precio total de la venta con descuento por mayor es de ' || resultado);
END;

EXEC Ej_precio_por_mayor(1);

--5. disponibilidad de un producto
CREATE OR REPLACE FUNCTION disponibilidad_producto(id_pro NUMBER) 
RETURN VARCHAR2 IS
    disponible VARCHAR2(45);
    cant number;
BEGIN
    SELECT cantidad INTO cant FROM productos WHERE id_productos = id_pro;
    
    IF cant>0 THEN
        disponible:='Si hay productos disponibles';
    ELSE
        disponible:='No hay productos disponibles';
    END IF;
    
    RETURN disponible;
END;

--ejec
CREATE OR REPLACE PROCEDURE Ej_disponibilidad_producto(IDE NUMBER)
IS
    resultado VARCHAR2 (45);
BEGIN
    resultado := disponibilidad_producto(IDE); 
    DBMS_OUTPUT.PUT_LINE(resultado);
END;

EXEC Ej_disponibilidad_producto(1);

--6. disponibilidad de un ingrediente
CREATE OR REPLACE FUNCTION disponibilidad_ingrediente(id_ing NUMBER) 
RETURN VARCHAR2 IS
    disponible VARCHAR2(45);
    cant number;
BEGIN
    SELECT cantidad INTO cant FROM ingredientes WHERE id_ingrediente = id_ing;
    
    IF cant>0 THEN
        disponible:='Si hay ingredientes disponibles';
    ELSE
        disponible:='No hay ingredientes disponibles';
    END IF;
    
    RETURN disponible;
END;

--ejec
CREATE OR REPLACE PROCEDURE Ej_disponibilidad_ingrediente(IDE NUMBER)
IS
    resultado VARCHAR2 (45);
BEGIN
    resultado := disponibilidad_ingrediente(IDE); 
    DBMS_OUTPUT.PUT_LINE(resultado);
END;

EXEC Ej_disponibilidad_ingrediente(1);

--7. consultar e imprimir categoria de un producto
CREATE OR REPLACE FUNCTION consult_categoria_producto(id_pro NUMBER) 
RETURN VARCHAR2 IS
    p_nom VARCHAR2(45);
    c_nom VARCHAR2(45);
    resultado VARCHAR2(100);
BEGIN
    SELECT p.nombre, c.nombre 
    INTO p_nom, c_nom 
    FROM productos p 
    JOIN CATEGORIA_PRODUCTOS c ON p.id_categoria = c.id_categoria
    WHERE id_productos = id_pro;
    
    resultado := 'El producto ' || p_nom || ' pertenece a la categoria ' || c_nom;
    RETURN resultado;
END;

--ejec
CREATE OR REPLACE PROCEDURE Ej_consult_categoria_producto(IDE NUMBER)
IS
    resultado VARCHAR2 (100);
BEGIN
    resultado := consult_categoria_producto(IDE); 
    DBMS_OUTPUT.PUT_LINE(resultado);
END;

EXEC Ej_consult_categoria_producto(1);


/*  -------------- CREACION DE PAQUETES ------------------*/

-- 1) PAQUETE DE VENTAS

-- Crear el paquete
CREATE OR REPLACE PACKAGE PAQUETE_VENTAS AS
  PROCEDURE INSERT_VENTAS (
    IDE VENTAS.ID_VENTA%TYPE,
    FECHA VENTAS.FECHA_VENTA%TYPE,
    CANT VENTAS.CANTIDAD%TYPE,
    PREC VENTAS.PRECIO%TYPE,
    ID_C VENTAS.ID_CLIENTE%TYPE,
    ID_P VENTAS.ID_PRODUCTOS%TYPE
  );

  FUNCTION DELETE_VENTAS (IDE VARCHAR2) RETURN VARCHAR2;

  PROCEDURE Ej_Func_Vent(IDE NUMBER);
  
  FUNCTION READ_VENTAS RETURN SYS_REFCURSOR;
END PAQUETE_VENTAS;
/

-- cuerpo del paquete
CREATE OR REPLACE PACKAGE BODY PAQUETE_VENTAS AS
  PROCEDURE INSERT_VENTAS (
    IDE VENTAS.ID_VENTA%TYPE,
    FECHA VENTAS.FECHA_VENTA%TYPE,
    CANT VENTAS.CANTIDAD%TYPE,
    PREC VENTAS.PRECIO%TYPE,
    ID_C VENTAS.ID_CLIENTE%TYPE,
    ID_P VENTAS.ID_PRODUCTOS%TYPE
  ) AS
  BEGIN
    INSERT INTO VENTAS (ID_VENTA, FECHA_VENTA, CANTIDAD, PRECIO, ID_CLIENTE, ID_PRODUCTOS)
    VALUES (IDE, FECHA, CANT, PREC, ID_C, ID_P);
    COMMIT;
  END INSERT_VENTAS;

  FUNCTION DELETE_VENTAS (IDE VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    DELETE FROM VENTAS
    WHERE ID_VENTA = IDE;
    COMMIT;
    RETURN 'Datos eliminados correctamente';
  END DELETE_VENTAS;

  PROCEDURE Ej_Func_Vent(IDE NUMBER) AS
    resultado VARCHAR2(100);
  BEGIN
    resultado := DELETE_VENTAS(IDE);
    DBMS_OUTPUT.PUT_LINE(resultado);
  END Ej_Func_Vent;

  FUNCTION READ_VENTAS RETURN SYS_REFCURSOR IS
    v_cursor SYS_REFCURSOR;
  BEGIN
    OPEN v_cursor FOR
      SELECT FECHA_VENTA, CANTIDAD, PRECIO, ID_CLIENTE, ID_PRODUCTOS
      FROM VENTAS
      ORDER BY FECHA_VENTA;
    RETURN v_cursor;
  END READ_VENTAS;
END PAQUETE_VENTAS;
/

-- 2) PAQUETE DE CLIENTES

-- Creacion del paquete
CREATE OR REPLACE PACKAGE PAQUETE_CLIENTES AS
  
  PROCEDURE INSERT_CLIENTES (
    IDE CLIENTE.ID_CLIENTE%TYPE,
    NOM CLIENTE.NOMBRE%TYPE,
    PRIMER_AP CLIENTE.PRIMER_APELLIDO%TYPE,
    SEGUNDO_AP CLIENTE.SEGUNDO_APELLIDO%TYPE,
    COR CLIENTE.CORREO%TYPE,
    NUMERO CLIENTE.NUMERO_TELEFONICO%TYPE,
    DIREC CLIENTE.DIRECCION%TYPE
  );

  PROCEDURE UPDATE_CLIENTES (
    IDE CLIENTE.ID_CLIENTE%TYPE,
    NOM CLIENTE.NOMBRE%TYPE,
    PRIMER_AP CLIENTE.PRIMER_APELLIDO%TYPE,
    SEGUNDO_AP CLIENTE.SEGUNDO_APELLIDO%TYPE,
    COR CLIENTE.CORREO%TYPE,
    NUMERO CLIENTE.NUMERO_TELEFONICO%TYPE,
    DIREC CLIENTE.DIRECCION%TYPE
  );

  FUNCTION DELETE_CLIENTES (IDE VARCHAR2) RETURN VARCHAR2;

  PROCEDURE Ej_Func_Client(IDE NUMBER);

  FUNCTION READ_CLIENTE RETURN SYS_REFCURSOR;
  
END PAQUETE_CLIENTES;
/
-- cuerpo del paquete
CREATE OR REPLACE PACKAGE BODY PAQUETE_CLIENTES AS

  PROCEDURE INSERT_CLIENTES (
    IDE CLIENTE.ID_CLIENTE%TYPE,
    NOM CLIENTE.NOMBRE%TYPE,
    PRIMER_AP CLIENTE.PRIMER_APELLIDO%TYPE,
    SEGUNDO_AP CLIENTE.SEGUNDO_APELLIDO%TYPE,
    COR CLIENTE.CORREO%TYPE,
    NUMERO CLIENTE.NUMERO_TELEFONICO%TYPE,
    DIREC CLIENTE.DIRECCION%TYPE
  ) AS
  BEGIN
    INSERT INTO CLIENTE (ID_CLIENTE, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO,
    NUMERO_TELEFONICO, DIRECCION)
    VALUES (IDE, NOM, PRIMER_AP, SEGUNDO_AP, COR, NUMERO, DIREC);
    COMMIT;
  END INSERT_CLIENTES;

  PROCEDURE UPDATE_CLIENTES (
    IDE CLIENTE.ID_CLIENTE%TYPE,
    NOM CLIENTE.NOMBRE%TYPE,
    PRIMER_AP CLIENTE.PRIMER_APELLIDO%TYPE,
    SEGUNDO_AP CLIENTE.SEGUNDO_APELLIDO%TYPE,
    COR CLIENTE.CORREO%TYPE,
    NUMERO CLIENTE.NUMERO_TELEFONICO%TYPE,
    DIREC CLIENTE.DIRECCION%TYPE
  ) AS
  BEGIN
    UPDATE CLIENTE 
    SET NOMBRE = NOM,
        PRIMER_APELLIDO = PRIMER_AP,
        SEGUNDO_APELLIDO = SEGUNDO_AP,
        CORREO = COR,
        NUMERO_TELEFONICO = NUMERO,
        DIRECCION = DIREC
    WHERE ID_CLIENTE = IDE;
    COMMIT;
  END UPDATE_CLIENTES;

  FUNCTION DELETE_CLIENTES (IDE VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    DELETE FROM CLIENTE
    WHERE ID_CLIENTE = IDE;
    COMMIT;
    RETURN 'Datos eliminados correctamente';
  END DELETE_CLIENTES;

  PROCEDURE Ej_Func_Client(IDE NUMBER) AS
    resultado VARCHAR2(100);
  BEGIN
    resultado := DELETE_CLIENTES(IDE);
    DBMS_OUTPUT.PUT_LINE(resultado);
  END Ej_Func_Client;

  FUNCTION READ_CLIENTE RETURN SYS_REFCURSOR IS
    v_cursor SYS_REFCURSOR;
  BEGIN
    OPEN v_cursor FOR
      SELECT NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, CORREO, NUMERO_TELEFONICO, DIRECCION
      FROM CLIENTE
      ORDER BY NOMBRE;
    RETURN v_cursor;
  END READ_CLIENTE;

END PAQUETE_CLIENTES;
/


-- 3) PAQUETE DE INVENTARIO ( procedimientos para actualizar las cantidades de productos en inventario )

-- Creacion del paquete
CREATE OR REPLACE PACKAGE PAQUETE_INVENTARIO AS
  
  PROCEDURE UPDATE_PRODUCTOS_CANTIDAD (
    p_id_producto IN NUMBER,
    p_nueva_cantidad IN NUMBER
  );

  FUNCTION VIEW_CATEGORY_CANT_DISPONIBLE RETURN SYS_REFCURSOR;

  FUNCTION VIEW_PRODUCTOS_CANT_BAJA RETURN SYS_REFCURSOR;

  FUNCTION VIEW_CATEGORY_CANT_TOTAL RETURN SYS_REFCURSOR;
  
END PAQUETE_INVENTARIO;
/

-- Crear el cuerpo del paquete
CREATE OR REPLACE PACKAGE BODY PAQUETE_INVENTARIO AS
  
  PROCEDURE UPDATE_PRODUCTOS_CANTIDAD (
    p_id_producto IN NUMBER,
    p_nueva_cantidad IN NUMBER
  ) AS
  BEGIN
    UPDATE PRODUCTOS
    SET CANTIDAD = p_nueva_cantidad
    WHERE ID_PRODUCTOS = p_id_producto;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Cantidad del producto actualizada con éxito.');
  END UPDATE_PRODUCTOS_CANTIDAD;

  FUNCTION VIEW_CATEGORY_CANT_DISPONIBLE RETURN SYS_REFCURSOR IS
    v_cursor SYS_REFCURSOR;
  BEGIN
    OPEN v_cursor FOR
      SELECT CP.NOMBRE AS NOMBRE_CATEGORIA, SUM(P.CANTIDAD) AS CANTIDAD_TOTAL
      FROM PRODUCTOS P
      JOIN CATEGORIA_PRODUCTOS CP ON P.ID_CATEGORIA = CP.ID_CATEGORIA
      GROUP BY CP.NOMBRE;
    RETURN v_cursor;
  END VIEW_CATEGORY_CANT_DISPONIBLE;

  FUNCTION VIEW_PRODUCTOS_CANT_BAJA RETURN SYS_REFCURSOR IS
    v_cursor SYS_REFCURSOR;
  BEGIN
    OPEN v_cursor FOR
      SELECT * FROM PRODUCTOS
      WHERE CANTIDAD < 20;
    RETURN v_cursor;
  END VIEW_PRODUCTOS_CANT_BAJA;

  FUNCTION VIEW_CATEGORY_CANT_TOTAL RETURN SYS_REFCURSOR IS
    v_cursor SYS_REFCURSOR;
  BEGIN
    OPEN v_cursor FOR
      SELECT CP.ID_CATEGORIA, CP.NOMBRE, CP.DESCRIPCION, COUNT(P.ID_PRODUCTOS) AS CANTIDAD_TOTAL
      FROM CATEGORIA_PRODUCTOS CP
      LEFT JOIN PRODUCTOS P ON CP.ID_CATEGORIA = P.ID_CATEGORIA
      GROUP BY CP.ID_CATEGORIA, CP.NOMBRE, CP.DESCRIPCION;
    RETURN v_cursor;
  END VIEW_CATEGORY_CANT_TOTAL;
END PAQUETE_INVENTARIO;
/


-- 4) PAQUETE DE PROVEEDORES


-- Creacion del paquete
CREATE OR REPLACE PACKAGE PAQUETE_PROVEEDORES AS
  PROCEDURE AGREGAR_PROVEEDOR (
    ID_PRO IN NUMBER,
    NOMBRE IN VARCHAR2,
    PAPELLIDO IN VARCHAR2,
    SAPELLIDO IN VARCHAR2,
    TELEFONO IN NUMBER,
    CORREO IN VARCHAR2,
    ESTADO IN VARCHAR2
  );

  PROCEDURE VER_PROVEEDOR_ESPECIFICO (ID_BUSCADO IN NUMBER);

  PROCEDURE ACTUALIZAR_PROVE (
    ID_BUSCADO IN NUMBER,
    NOMBRE IN VARCHAR2,
    PAPELLIDO IN VARCHAR2,
    SAPELLIDO IN VARCHAR2,
    NUMERO IN NUMBER,
    CORREO IN VARCHAR2,
    EST IN VARCHAR2
  );

  PROCEDURE ELIMINAR_PROVEEDOR_ESPECIFICO (IDBUSCADO IN NUMBER);
END PAQUETE_PROVEEDORES;
/

-- cuerpo del paquete
CREATE OR REPLACE PACKAGE BODY PAQUETE_PROVEEDORES AS
  PROCEDURE AGREGAR_PROVEEDOR (
    ID_PRO IN NUMBER,
    NOMBRE IN VARCHAR2,
    PAPELLIDO IN VARCHAR2,
    SAPELLIDO IN VARCHAR2,
    TELEFONO IN NUMBER,
    CORREO IN VARCHAR2,
    ESTADO IN VARCHAR2
  ) AS
  BEGIN
    INSERT INTO PROVEEDORES (ID_PROVEEDOR, NOMBRE_PROVEEDOR, PRIMER_APELLIDO,
                              SEGUNDO_APELLIDO, NUMERO_TELEFONICO, CORREO_ELECTRONICO, ESTADO)
    VALUES (ID_PRO, NOMBRE, PAPELLIDO, SAPELLIDO, TELEFONO, CORREO, ESTADO);
    COMMIT;
  END AGREGAR_PROVEEDOR;

  PROCEDURE VER_PROVEEDOR_ESPECIFICO (ID_BUSCADO IN NUMBER) AS
  BEGIN
    FOR PROVEEDOR_C IN (SELECT * FROM PROVEEDORES WHERE ID_PROVEEDOR = ID_BUSCADO) LOOP
      -- Hacer algo con la información del proveedor (por ejemplo, imprimir en la salida)
      DBMS_OUTPUT.PUT_LINE(PROVEEDOR_C.ID_PROVEEDOR || ' ' || PROVEEDOR_C.NOMBRE_PROVEEDOR || ' ' ||
                           PROVEEDOR_C.PRIMER_APELLIDO || ' ' || PROVEEDOR_C.SEGUNDO_APELLIDO || ' ' ||
                           PROVEEDOR_C.NUMERO_TELEFONICO || ' ' || PROVEEDOR_C.CORREO_ELECTRONICO || ' ' ||
                           PROVEEDOR_C.ESTADO);
    END LOOP;
  END VER_PROVEEDOR_ESPECIFICO;

  PROCEDURE ACTUALIZAR_PROVE (
    ID_BUSCADO IN NUMBER,
    NOMBRE IN VARCHAR2,
    PAPELLIDO IN VARCHAR2,
    SAPELLIDO IN VARCHAR2,
    NUMERO IN NUMBER,
    CORREO IN VARCHAR2,
    EST IN VARCHAR2
  ) AS
  BEGIN
    UPDATE PROVEEDORES
    SET NOMBRE_PROVEEDOR = NOMBRE,
        PRIMER_APELLIDO = PAPELLIDO,
        SEGUNDO_APELLIDO = SAPELLIDO,
        NUMERO_TELEFONICO = NUMERO,
        CORREO_ELECTRONICO = CORREO,
        ESTADO = EST
    WHERE ID_PROVEEDOR = ID_BUSCADO;
    COMMIT;
  END ACTUALIZAR_PROVE;

  PROCEDURE ELIMINAR_PROVEEDOR_ESPECIFICO (IDBUSCADO IN NUMBER) AS
  BEGIN
    DELETE FROM PROVEEDORES WHERE ID_PROVEEDOR = IDBUSCADO;
    COMMIT;
  END ELIMINAR_PROVEEDOR_ESPECIFICO;
END PAQUETE_PROVEEDORES;
/



-- 5) PAQUETE DE COMPRAS

-- Creacion del paquete
CREATE OR REPLACE PACKAGE PAQUETE_COMPRAS AS
  PROCEDURE insertar_compra (
    p_id_compra IN NUMBER,
    p_fecha_compra IN DATE,
    p_id_proveedor IN NUMBER,
    p_id_producto IN NUMBER,
    p_cantidad IN INT,
    p_precio IN INT,
    p_total IN INT
  );

  PROCEDURE actualizar_compra (
    p_id_compra IN NUMBER,
    p_cantidad IN INT,
    p_precio IN INT,
    p_total IN INT
  );

  FUNCTION calcular_total_compras RETURN INT;

  FUNCTION proveedor_con_mas_compras RETURN VARCHAR2;

  PROCEDURE OBTENER_COMPRAS_POR_PROVEEDOR (p_id_proveedor IN NUMBER);
END PAQUETE_COMPRAS;
/

-- cuerpo del paquete
CREATE OR REPLACE PACKAGE BODY PAQUETE_COMPRAS AS
  PROCEDURE insertar_compra (
    p_id_compra IN NUMBER,
    p_fecha_compra IN DATE,
    p_id_proveedor IN NUMBER,
    p_id_producto IN NUMBER,
    p_cantidad IN INT,
    p_precio IN INT,
    p_total IN INT
  ) AS
  BEGIN
    INSERT INTO COMPRAS (ID_COMPRA, FECHA_COMPRA, ID_PROVEEDOR, ID_PRODUCTOS,
                          CANTIDAD, PRECIO, TOTAL)
    VALUES (p_id_compra, p_fecha_compra, p_id_proveedor, p_id_producto, p_cantidad,
            p_precio, p_total);
    COMMIT;
  END insertar_compra;

  PROCEDURE actualizar_compra (
    p_id_compra IN NUMBER,
    p_cantidad IN INT,
    p_precio IN INT,
    p_total IN INT
  ) AS
  BEGIN
    UPDATE COMPRAS
    SET CANTIDAD = p_cantidad,
        PRECIO = p_precio,
        TOTAL = p_total
    WHERE ID_COMPRA = p_id_compra;
    COMMIT;
  END actualizar_compra;

  FUNCTION calcular_total_compras RETURN INT IS
    v_total INT := 0;
  BEGIN
    SELECT SUM(TOTAL) INTO v_total FROM COMPRAS;
    RETURN v_total;
  END calcular_total_compras;

  FUNCTION proveedor_con_mas_compras RETURN VARCHAR2 IS
    v_proveedor VARCHAR2(50);
  BEGIN
    SELECT P.NOMBRE_PROVEEDOR
    INTO v_proveedor
    FROM COMPRAS C
    JOIN PROVEEDORES P ON C.ID_PROVEEDOR = P.ID_PROVEEDOR
    GROUP BY P.NOMBRE_PROVEEDOR
    ORDER BY COUNT(C.ID_COMPRA) DESC
    FETCH FIRST 1 ROW ONLY;
    RETURN v_proveedor;
  END proveedor_con_mas_compras;

  PROCEDURE OBTENER_COMPRAS_POR_PROVEEDOR (p_id_proveedor IN NUMBER) IS
    CURSOR c_compras_proveedor IS
      SELECT ID_COMPRA, FECHA_COMPRA
      FROM COMPRAS
      WHERE ID_PROVEEDOR = p_id_proveedor;

    v_id_compra_proveedor COMPRAS.ID_COMPRA%TYPE;
    v_fecha_compra_proveedor COMPRAS.FECHA_COMPRA%TYPE;
  BEGIN
    OPEN c_compras_proveedor;
    LOOP
      FETCH c_compras_proveedor INTO v_id_compra_proveedor, v_fecha_compra_proveedor;

      EXIT WHEN c_compras_proveedor%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('ID Compra: ' || v_id_compra_proveedor || ', Fecha Compra: ' || v_fecha_compra_proveedor);
    END LOOP;
    CLOSE c_compras_proveedor;
  END OBTENER_COMPRAS_POR_PROVEEDOR;
END PAQUETE_COMPRAS;
/



-- 6) PAQUETE DE INGREDIENTES

-- Creacion del paquete
CREATE OR REPLACE PACKAGE PAQUETE_INGREDIENTES AS
  PROCEDURE AGREGAR_INGREDIENTE (
    ID_INGREDIENTE IN NUMBER,
    NOMBRE IN VARCHAR2,
    UNIDAD IN VARCHAR2,
    PRECIO NUMBER,
    CANTIDAD IN NUMBER,
    ID_PROVEEDOR IN NUMBER
  );

  PROCEDURE ACTUALIZAR_INGREDIENTE_PRECIO (
    IDINGRE IN NUMBER,
    PRECIONUEVO IN NUMBER
  );

  PROCEDURE ACTUALIZAR_CANTIDAD_INGREDIENTE (
    ID_BUSCADO IN NUMBER,
    CANTIDAD_NUEVA IN NUMBER
  );

  PROCEDURE ELIMINAR_INGREDIENTE (
    ID_BUSCADO IN NUMBER
  );

  PROCEDURE ACTUALIZAR_INGREDIENTES (
    ID_BUSCADO IN NUMBER,
    NOMBRE IN VARCHAR2,
    UNIDAD IN VARCHAR2,
    PRECIONU IN NUMBER,
    CANTIDADNU IN NUMBER,
    ID_PROV IN NUMBER
  );
END PAQUETE_INGREDIENTES;
/

-- cuerpo del paquete
CREATE OR REPLACE PACKAGE BODY PAQUETE_INGREDIENTES AS
  PROCEDURE AGREGAR_INGREDIENTE (
    ID_INGREDIENTE IN NUMBER,
    NOMBRE IN VARCHAR2,
    UNIDAD IN VARCHAR2,
    PRECIO NUMBER,
    CANTIDAD IN NUMBER,
    ID_PROVEEDOR IN NUMBER
  ) AS
  BEGIN
    INSERT INTO INGREDIENTES (ID_INGREDIENTE, NOMBRE_INGREDIENTE, UNIDAD_MEDIDA,
                               PRECIO, CANTIDAD, ID_PROVEEDOR)
    VALUES (ID_INGREDIENTE, NOMBRE, UNIDAD, PRECIO, CANTIDAD, ID_PROVEEDOR);
    COMMIT;
  END AGREGAR_INGREDIENTE;

  PROCEDURE ACTUALIZAR_INGREDIENTE_PRECIO (
    IDINGRE IN NUMBER,
    PRECIONUEVO IN NUMBER
  ) AS
  BEGIN
    UPDATE INGREDIENTES SET PRECIO = PRECIONUEVO WHERE ID_INGREDIENTE = IDINGRE;
    COMMIT;
  END ACTUALIZAR_INGREDIENTE_PRECIO;

  PROCEDURE ACTUALIZAR_CANTIDAD_INGREDIENTE (
    ID_BUSCADO IN NUMBER,
    CANTIDAD_NUEVA IN NUMBER
  ) AS
  BEGIN
    UPDATE INGREDIENTES SET CANTIDAD = CANTIDAD_NUEVA WHERE ID_INGREDIENTE = ID_BUSCADO;
    COMMIT;
  END ACTUALIZAR_CANTIDAD_INGREDIENTE;

  PROCEDURE ELIMINAR_INGREDIENTE (
    ID_BUSCADO IN NUMBER
  ) AS
  BEGIN
    DELETE FROM INGREDIENTES WHERE ID_INGREDIENTE = ID_BUSCADO;
    COMMIT;
  END ELIMINAR_INGREDIENTE;

  PROCEDURE ACTUALIZAR_INGREDIENTES (
    ID_BUSCADO IN NUMBER,
    NOMBRE IN VARCHAR2,
    UNIDAD IN VARCHAR2,
    PRECIONU IN NUMBER,
    CANTIDADNU IN NUMBER,
    ID_PROV IN NUMBER
  ) AS
  BEGIN
    UPDATE INGREDIENTES
    SET NOMBRE_INGREDIENTE = NOMBRE,
        UNIDAD_MEDIDA = UNIDAD,
        PRECIO = PRECIONU,
        CANTIDAD = CANTIDADNU,
        ID_PROVEEDOR = ID_PROV
    WHERE ID_INGREDIENTE = ID_BUSCADO;
    COMMIT;
  END ACTUALIZAR_INGREDIENTES;
END PAQUETE_INGREDIENTES;
/




-- 7) PAQUETE DE ACTUALIZACION DE PRECIOS

-- Creacio del paquete
CREATE OR REPLACE PACKAGE PAQUETE_UPDATE_PRECIOS AS
  PROCEDURE ACTUALIZAR_INGREDIENTE_PRECIO (
    IDINGRE IN NUMBER,
    PRECIONUEVO IN NUMBER
  );

  PROCEDURE UPDATE_PRODUCTOS_PRECIO (
    p_id_producto IN NUMBER,
    p_nuevo_precio IN NUMBER
  );
END PAQUETE_UPDATE_PRECIOS;
/

-- cuerpo del paquete
CREATE OR REPLACE PACKAGE BODY PAQUETE_UPDATE_PRECIOS AS
  PROCEDURE ACTUALIZAR_INGREDIENTE_PRECIO (
    IDINGRE IN NUMBER,
    PRECIONUEVO IN NUMBER
  ) AS
  BEGIN
    UPDATE INGREDIENTES SET PRECIO = PRECIONUEVO WHERE ID_INGREDIENTE = IDINGRE;
    COMMIT;
  END ACTUALIZAR_INGREDIENTE_PRECIO;

  PROCEDURE UPDATE_PRODUCTOS_PRECIO (
    p_id_producto IN NUMBER,
    p_nuevo_precio IN NUMBER
  ) AS
  BEGIN
    UPDATE PRODUCTOS SET PRECIO = p_nuevo_precio WHERE ID_PRODUCTOS = p_id_producto;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Precio del producto actualizado con éxito.');
  END UPDATE_PRODUCTOS_PRECIO;
END PAQUETE_UPDATE_PRECIOS;
/


-- 8) PAQUETE DE INFORMACION DE PRODUCTOS

-- Crear el paquete
CREATE OR REPLACE PACKAGE PAQUETE_INFO_PRODUCTOS AS
  FUNCTION READ_CATEGORY (
    p_id_categoria IN NUMBER
  ) RETURN VARCHAR2;

  FUNCTION READ_PRODUCTOS (
    p_id_producto IN NUMBER
  ) RETURN VARCHAR2;

END PAQUETE_INFO_PRODUCTOS;
/

-- Crear el cuerpo del paquete
CREATE OR REPLACE PACKAGE BODY PAQUETE_INFO_PRODUCTOS AS
  FUNCTION READ_CATEGORY (
    p_id_categoria IN NUMBER
  ) RETURN VARCHAR2 AS
    v_info_categoria VARCHAR2(200);
  BEGIN
    SELECT 'ID: ' || ID_CATEGORIA || ', Nombre: ' || NOMBRE || ', Descripción: ' || DESCRIPCION
    INTO v_info_categoria
    FROM CATEGORIA_PRODUCTOS
    WHERE ID_CATEGORIA = p_id_categoria;

    RETURN v_info_categoria;
  END READ_CATEGORY;

  FUNCTION READ_PRODUCTOS (
    p_id_producto IN NUMBER
  ) RETURN VARCHAR2 AS
    v_info_producto VARCHAR2(200);
  BEGIN
    SELECT 'ID: ' || ID_PRODUCTOS || ', Nombre: ' || NOMBRE || ', Cantidad: ' || CANTIDAD ||
           ', Descripción: ' || DESCRIPCION || ', Tamaño: ' || TAMANO || ', Precio: ' || PRECIO
    INTO v_info_producto
    FROM PRODUCTOS
    WHERE ID_PRODUCTOS = p_id_producto;

    RETURN v_info_producto;
  END READ_PRODUCTOS;
END PAQUETE_INFO_PRODUCTOS;
/


-- 9 PAQUETE DE REPORTES FINANCIEROS ( contiene dos funciones. una que calcula las ganancias totales durante un periodo especifico y otra funcion que calcula los gastos totales realizados por todas las compras. )

-- Creacion del paquete
CREATE OR REPLACE PACKAGE PAQUETE_REPORTES_FINANCIEROS AS
  FUNCTION calcular_ganancias_por_periodo(
    p_fecha_inicio IN DATE,
    p_fecha_fin IN DATE
  ) RETURN NUMBER;

  FUNCTION calcular_gastos_totales RETURN NUMBER;
END PAQUETE_REPORTES_FINANCIEROS;
/

-- cuerpo del paquete
CREATE OR REPLACE PACKAGE BODY PAQUETE_REPORTES_FINANCIEROS AS
  FUNCTION calcular_ganancias_por_periodo(
    p_fecha_inicio IN DATE,
    p_fecha_fin IN DATE
  ) RETURN NUMBER AS
    v_ganancias NUMBER := 0;
  BEGIN
    SELECT NVL(SUM(PRECIO * CANTIDAD), 0)
    INTO v_ganancias
    FROM VENTAS
    WHERE FECHA_VENTA BETWEEN p_fecha_inicio AND p_fecha_fin;

    RETURN v_ganancias;
  END calcular_ganancias_por_periodo;

  FUNCTION calcular_gastos_totales RETURN NUMBER AS
    v_gastos NUMBER := 0;
  BEGIN
    SELECT NVL(SUM(TOTAL), 0)
    INTO v_gastos
    FROM COMPRAS;

    RETURN v_gastos;
  END calcular_gastos_totales;
END PAQUETE_REPORTES_FINANCIEROS;
/


-- 10) PAQUETE DE ADMINISTRACION DE CATEGORIAS

-- Creacion del paquete
CREATE OR REPLACE PACKAGE PAQUETE_ADMIN_CATEGORIAS AS
  PROCEDURE ADD_CATEGORY (
    p_id_categoria IN NUMBER,
    p_nombre IN VARCHAR2,
    p_descripcion IN VARCHAR2
  );

  PROCEDURE DELETE_CATEGORY (
    p_id_categoria IN NUMBER
  );

  PROCEDURE UPDATE_CATEGORY_NAME (
    p_id_categoria IN NUMBER,
    p_nuevo_nombre IN VARCHAR2
  );

END PAQUETE_ADMIN_CATEGORIAS;
/

-- cuerpo del paquete
CREATE OR REPLACE PACKAGE BODY PAQUETE_ADMIN_CATEGORIAS AS
  PROCEDURE ADD_CATEGORY (
    p_id_categoria IN NUMBER,
    p_nombre IN VARCHAR2,
    p_descripcion IN VARCHAR2
  ) AS
  BEGIN
    INSERT INTO CATEGORIA_PRODUCTOS (ID_CATEGORIA, NOMBRE, DESCRIPCION)
    VALUES (p_id_categoria, p_nombre, p_descripcion);    
    COMMIT;
  END ADD_CATEGORY;

  PROCEDURE DELETE_CATEGORY (
    p_id_categoria IN NUMBER
  ) AS
  BEGIN
    DELETE FROM CATEGORIA_PRODUCTOS
    WHERE ID_CATEGORIA = p_id_categoria;
    COMMIT;
  END DELETE_CATEGORY;

  PROCEDURE UPDATE_CATEGORY_NAME (
    p_id_categoria IN NUMBER,
    p_nuevo_nombre IN VARCHAR2
  ) AS
  BEGIN
    UPDATE CATEGORIA_PRODUCTOS
    SET NOMBRE = p_nuevo_nombre
    WHERE ID_CATEGORIA = p_id_categoria;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Descripción de la categoría actualizada con éxito.');
  END UPDATE_CATEGORY_NAME;
END PAQUETE_ADMIN_CATEGORIAS;
/


/* --------------- CREACION DE TRIGGERS ----------------------  */


-- 1)
-- Trigger para impedir la eliminación si la cantidad es mayor a 0

CREATE OR REPLACE TRIGGER TRG_EVITAR_ELIMINACION
BEFORE DELETE ON INGREDIENTES
FOR EACH ROW
BEGIN
    IF :OLD.CANTIDAD > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar el ingrediente porque tiene una cantidad mayor a 0.');
    END IF;
END;
/


-- 2) Trigger para Impedir Eliminación de Categorías con Productos Asociados

CREATE OR REPLACE TRIGGER TRG_PREVENIR_ELIMINACION_CATEGORIA
BEFORE DELETE ON CATEGORIA_PRODUCTOS
FOR EACH ROW
DECLARE
    v_productos_en_categoria NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_productos_en_categoria
    FROM PRODUCTOS
    WHERE ID_CATEGORIA = :OLD.ID_CATEGORIA;

    IF v_productos_en_categoria > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar una categoría con productos asociados.');
    END IF;
END;
/

-- 3) Trigger para Actualizar Precio al Cambiar Tamaño del Producto

CREATE OR REPLACE TRIGGER TRG_ACTUALIZAR_PRECIO_POR_TAMANO
BEFORE UPDATE OF TAMANO ON PRODUCTOS
FOR EACH ROW
BEGIN
    IF :OLD.TAMANO != :NEW.TAMANO THEN
        :NEW.PRECIO := :NEW.PRECIO * 1.1; 
    END IF;
END;


-- 4) Trigger para impedir la inserción de un ingrediente con cantidad negativa:

CREATE OR REPLACE TRIGGER TRG_EVITAR_INSERCION
BEFORE INSERT ON INGREDIENTES
FOR EACH ROW
BEGIN
    IF :NEW.CANTIDAD < 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se puede insertar el ingrediente con cantidad negativa.');
    END IF;
END;
/


-- 5) Trigger para Controlar la Cantidad de Productos al Insertar o Actualizar:
-- trigger evita que la cantidad de productos sea negativa.

CREATE OR REPLACE TRIGGER TRG_CONTROLAR_CANTIDAD_PRODUCTOS
BEFORE INSERT OR UPDATE ON PRODUCTOS
FOR EACH ROW
BEGIN
    IF :NEW.CANTIDAD < 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'La cantidad de productos no puede ser negativa.');
    END IF;
END;
/
































